### ISSUE TITLE
Undefined pairingTopic for first connect

### ISSUE THREAD

**Issue by faboweb** [cosmology-tech/cosmos-kit#228] opened 2023-06-12 10:51 UTC
https://github.com/cosmology-tech/cosmos-kit/blob/4eb9c692ecd39aec974508fb8838241774c9ba42/packages/walletconnect/src/client.ts#L412

On a reconnect the wallet connect library throws here:

`{'core/pairing/pairing'} 'No matching key. pairing: undefined'` trying to clean up existing pairings

**Comment by liujun93** [comment] 2023-06-13 04:09
@faboweb Can you describe the steps to reproduce the error? And, is it on mobile or desktop?

**Comment by liujun93** [comment] 2023-06-14 02:26
@twhy An issue from `Cosmos Kit <> Leap` that probably can be solved together
>  I found one minor bug, basically, first time I try to connect using wallet-connect v2 keplr-mobile, everything works fine. But, once there is pairing but no session, that is after I disconnect, and than try to connect, what happens is qrCode comes up first time, but if I reject request on wallet, than connectResp.uri always comes undefined on calling client?.connect([...]) with proper chains Ids, even though I get prompts on wallet, it's just connectResp.uri coming to be undefined which results in qrUrl set to be undefined and we cannot reopen Modal even if we want to (which is bit opposite to ideal behavior since we will have pairings, it's just we want the user to have functionality to scan qrCode even if they had previously connected a wallet and later disconnect it.)
Here is sample: https://www.loom.com/share/2f699c5260ed435e97a9a7fe842ae72d

**Comment by twhy** [comment] 2023-06-28 01:43
@faboweb We can't reproduce this issue and will close it. Please provide a minimum codebase that can help reproduce the issue and reopen this issue or open a new issue.

**Closed by twhy** 2023-06-28 01:43 UTC
